name: Sync Leetcode

on:
  workflow_dispatch: # Allows you to manually trigger the sync at any time
  schedule:
    - cron: "0 8 * * 6" # Automatically runs every Saturday at 8:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: "leetcode-solutions" # The folder inside your repo where code goes
          verbose: true
